// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace StudyAppV2.Migrations
{
    [DbContext(typeof(TermContext))]
    partial class TermContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("StudyAppV2.Models.Study", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Study");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Study");
                });

            modelBuilder.Entity("StudyAppV2.Models.Term", b =>
                {
                    b.HasBaseType("StudyAppV2.Models.Study");

                    b.Property<string>("Answers")
                        .HasColumnType("TEXT");

                    b.Property<string>("Definitions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Questions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terms")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Term");
                });
#pragma warning restore 612, 618
        }
    }
}
