// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace StudyApp.Migrations
{
    [DbContext(typeof(TermContext))]
    partial class TermContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("StudyApp.Models.Term", b =>
                {
                    b.Property<int>("TermID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ask")
                        .HasColumnType("TEXT");

                    b.Property<string>("Def")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fact")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("TermName")
                        .HasColumnType("TEXT");

                    b.HasKey("TermID");

                    b.ToTable("Term");
                });
#pragma warning restore 612, 618
        }
    }
}
